# Generated by Django 4.2.6 on 2025-05-24 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminder',
            old_name='date',
            new_name='delivery_date',
        ),
        migrations.RenameField(
            model_name='reminder',
            old_name='time',
            new_name='delivery_time',
        ),
    ]
